"""Phase 1 source registry for the AMR data pipeline.

Single source of truth for all sources to be scraped and ingested.
Each source is defined as a SourceConfig with full metadata.

Reference: SPEC-01, Section 1 and Section 4.
"""

from src.models import SourceConfig

PHASE_1_SOURCES: list[SourceConfig] = [
    # --- Static HTML Sources ---
    SourceConfig(
        source_id="who-amr-topics",
        title="WHO Health Topics - Antimicrobial Resistance",
        url="https://www.who.int/health-topics/antimicrobial-resistance",
        organisation="WHO",
        scraping_method="scrapy",
        expertise_level="beginner",
        content_category="learning",
        document_format="html",
        authority_tier=1,
        crawl_depth=2,
    ),
    SourceConfig(
        source_id="cdc-amr-hub",
        title="CDC Antimicrobial Resistance Hub",
        url="https://www.cdc.gov/antimicrobial-resistance/about/index.html",
        organisation="CDC",
        scraping_method="scrapy",
        expertise_level="beginner",
        content_category="learning",
        document_format="html",
        authority_tier=1,
        crawl_depth=2,
    ),
    SourceConfig(
        source_id="fao-amr",
        title="FAO Antimicrobial Resistance",
        url="https://www.fao.org/antimicrobial-resistance/background/what-is-it/en/",
        organisation="FAO",
        scraping_method="scrapy",
        expertise_level="beginner",
        content_category="learning",
        document_format="html",
        authority_tier=1,
        crawl_depth=2,
    ),
    SourceConfig(
        source_id="uk-amr-plan",
        title="UK 5-Year AMR Action Plan 2024-2029",
        url="https://www.gov.uk/government/publications/uk-5-year-action-plan-for-antimicrobial-resistance-2024-to-2029/confronting-antimicrobial-resistance-2024-to-2029",
        organisation="UK Government",
        scraping_method="scrapy",
        expertise_level="intermediate",
        content_category="action_plan",
        document_format="html",
        authority_tier=1,
        crawl_depth=2,
    ),
    SourceConfig(
        source_id="lancet-gram-pmc",
        title="Lancet GRAM Study 2019 (PMC)",
        url="https://pmc.ncbi.nlm.nih.gov/articles/PMC8841637/",
        organisation="The Lancet / PMC",
        scraping_method="scrapy",
        expertise_level="advanced",
        content_category="impact",
        document_format="html",
        authority_tier=2,
        crawl_depth=2,
    ),
    # --- PDF Sources ---
    SourceConfig(
        source_id="who-gap-2015",
        title="WHO Global Action Plan on AMR (2015)",
        url="https://www.who.int/publications/i/item/9789241509763",
        organisation="WHO",
        scraping_method="docling",
        expertise_level="intermediate",
        content_category="action_plan",
        document_format="pdf",
        authority_tier=1,
    ),
    SourceConfig(
        source_id="us-carb-nap",
        title="US CARB National Action Plan 2020-2025",
        url="https://www.hhs.gov/sites/default/files/carb-national-action-plan-2020-2025.pdf",
        organisation="US HHS",
        scraping_method="docling",
        expertise_level="intermediate",
        content_category="action_plan",
        document_format="pdf",
        authority_tier=1,
    ),
    SourceConfig(
        source_id="un-declaration-2024",
        title="UN Political Declaration on AMR (2024)",
        url="https://www.un.org/pga/wp-content/uploads/sites/108/2024/09/FINAL-Text-AMR-to-PGA.pdf",
        organisation="United Nations",
        scraping_method="docling",
        expertise_level="intermediate",
        content_category="action_plan",
        document_format="pdf",
        authority_tier=1,
    ),
    SourceConfig(
        source_id="world-bank-amr",
        title="World Bank - Drug-Resistant Infections: A Threat to Our Economic Future",
        url="https://documents1.worldbank.org/curated/en/323311493396993758/pdf/final-report.pdf",
        organisation="World Bank",
        scraping_method="docling",
        expertise_level="intermediate",
        content_category="impact",
        document_format="pdf",
        authority_tier=1,
    ),
    SourceConfig(
        source_id="cdc-threats-report",
        title="CDC Antibiotic Resistance Threats in the United States",
        url="https://stacks.cdc.gov/view/cdc/82532",
        organisation="CDC",
        scraping_method="docling",
        expertise_level="intermediate",
        content_category="risk",
        document_format="pdf",
        authority_tier=1,
    ),
    # --- New Static HTML Sources: Resistance Mechanisms ---
    SourceConfig(
        source_id="react-resistance-mechanisms",
        title="Resistance Mechanisms in Bacteria - ReAct",
        url="https://www.reactgroup.org/toolbox/understand/antibiotic-resistance/resistance-mechanisms-in-bacteria/",
        organisation="ReAct Group",
        scraping_method="scrapy",
        expertise_level="beginner",
        content_category="learning",
        document_format="html",
        authority_tier=2,
        crawl_depth=2,
    ),
    SourceConfig(
        source_id="react-horizontal-gene-transfer",
        title="Transfer of Antibiotic Resistance - ReAct",
        url="https://www.reactgroup.org/toolbox/understand/antibiotic-resistance/transfer-of-antibiotic-resistance/",
        organisation="ReAct Group",
        scraping_method="scrapy",
        expertise_level="beginner",
        content_category="learning",
        document_format="html",
        authority_tier=2,
        crawl_depth=2,
    ),
    SourceConfig(
        source_id="libretexts-amr-mechanisms",
        title="Mechanisms for Resistance - Biology LibreTexts (OpenStax Microbiology)",
        url="https://bio.libretexts.org/Courses/Manchester_Community_College_(MCC)/Remix_of_Openstax%3AMicrobiology_by_Parker_Schneegurt_et_al/11%3A_Control_of_Microbial_Growth/11.07",
        organisation="LibreTexts / OpenStax",
        scraping_method="scrapy",
        expertise_level="intermediate",
        content_category="learning",
        document_format="html",
        authority_tier=3,
        crawl_depth=1,
    ),
    SourceConfig(
        source_id="pmc-amr-mechanisms-overview-2019",
        title="An Overview of Antimicrobial Resistance Mechanisms (PMC)",
        url="https://pmc.ncbi.nlm.nih.gov/articles/PMC6604941/",
        organisation="PMC / NCBI",
        scraping_method="scrapy",
        expertise_level="advanced",
        content_category="data",
        document_format="html",
        authority_tier=2,
        crawl_depth=1,
    ),
    SourceConfig(
        source_id="pmc-amr-mechanisms-genetic-2016",
        title="Mechanisms of Antibiotic Resistance (Evolutionary & Genetic) (PMC)",
        url="https://pmc.ncbi.nlm.nih.gov/articles/PMC4888801/",
        organisation="PMC / NCBI",
        scraping_method="scrapy",
        expertise_level="advanced",
        content_category="data",
        document_format="html",
        authority_tier=2,
        crawl_depth=1,
    ),
    SourceConfig(
        source_id="pmc-mayo-beta-lactam-glycopeptide-2012",
        title="Beta-Lactam, Glycopeptide, and Fluoroquinolone Resistance - Mayo Clinic Proceedings",
        url="https://pmc.ncbi.nlm.nih.gov/articles/PMC3498059/",
        organisation="Mayo Clinic Proceedings / PMC",
        scraping_method="scrapy",
        expertise_level="advanced",
        content_category="data",
        document_format="html",
        authority_tier=2,
        crawl_depth=1,
    ),
    SourceConfig(
        source_id="pmc-efflux-pumps-2023",
        title="Role of Bacterial Efflux Pumps in Antimicrobial Resistance (PMC)",
        url="https://pmc.ncbi.nlm.nih.gov/articles/PMC10268834/",
        organisation="PMC / NCBI",
        scraping_method="scrapy",
        expertise_level="advanced",
        content_category="data",
        document_format="html",
        authority_tier=2,
        crawl_depth=1,
    ),
    # --- New Static HTML Sources: Action Plans & Policy ---
    SourceConfig(
        source_id="eu-one-health-action-plan",
        title="EU One Health Action Plan Against AMR (EUR-Lex)",
        url="https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:52017DC0339",
        organisation="European Commission",
        scraping_method="scrapy",
        expertise_level="advanced",
        content_category="action_plan",
        document_format="html",
        authority_tier=1,
        crawl_depth=1,
    ),
    SourceConfig(
        source_id="cdc-stewardship-hospital",
        title="CDC Core Elements of Hospital Antibiotic Stewardship",
        url="https://www.cdc.gov/antibiotic-use/hcp/core-elements/hospital.html",
        organisation="CDC",
        scraping_method="scrapy",
        expertise_level="intermediate",
        content_category="action_plan",
        document_format="html",
        authority_tier=1,
        crawl_depth=2,
    ),
    # --- New Static HTML Sources: Public Education & Awareness ---
    SourceConfig(
        source_id="who-waaw-campaign",
        title="World AMR Awareness Week Campaign - WHO",
        url="https://www.who.int/campaigns/world-amr-awareness-week",
        organisation="WHO",
        scraping_method="scrapy",
        expertise_level="beginner",
        content_category="learning",
        document_format="html",
        authority_tier=1,
        crawl_depth=2,
    ),
    SourceConfig(
        source_id="cdc-be-antibiotics-aware-toolkit",
        title="Be Antibiotics Aware Partner Toolkit - CDC",
        url="https://www.cdc.gov/antibiotic-use/php/usaaw-partner-toolkit/index.html",
        organisation="CDC",
        scraping_method="scrapy",
        expertise_level="beginner",
        content_category="learning",
        document_format="html",
        authority_tier=1,
        crawl_depth=2,
    ),
    SourceConfig(
        source_id="cdc-patient-education-resources",
        title="Patient Education Resources Collection - CDC Antibiotic Use",
        url="https://www.cdc.gov/antibiotic-use/communication-resources/index.html",
        organisation="CDC",
        scraping_method="scrapy",
        expertise_level="beginner",
        content_category="learning",
        document_format="html",
        authority_tier=1,
        crawl_depth=2,
    ),
    SourceConfig(
        source_id="react-educational-materials",
        title="Educational Materials Collection + Alforja Educativa - ReAct",
        url="https://w3ww.reactgroup.org/news-and-views/educational-material/",
        organisation="ReAct Group",
        scraping_method="scrapy",
        expertise_level="beginner",
        content_category="learning",
        document_format="html",
        authority_tier=2,
        crawl_depth=2,
    ),
    SourceConfig(
        source_id="react-toolbox-raise-awareness",
        title="ReAct Toolbox - Raise Awareness & Education Section",
        url="https://www.reactgroup.org/toolbox/raise-awareness/education-and-training/",
        organisation="ReAct Group",
        scraping_method="scrapy",
        expertise_level="intermediate",
        content_category="learning",
        document_format="html",
        authority_tier=2,
        crawl_depth=2,
    ),
    SourceConfig(
        source_id="cdc-usaaw-toolkit",
        title="US Antibiotic Awareness Week (USAAW) Toolkit - CDC",
        url="https://www.cdc.gov/antimicrobial-resistance/communication-resources/usaaw.html",
        organisation="CDC",
        scraping_method="scrapy",
        expertise_level="beginner",
        content_category="learning",
        document_format="html",
        authority_tier=1,
        crawl_depth=2,
    ),
    # --- New Static HTML Sources: Clinical Guidelines & Policy ---
    SourceConfig(
        source_id="who-ipc-amr-guidelines",
        title="Infection Prevention and Control Guidelines - WHO AMR",
        url="https://www.who.int/teams/integrated-health-services/infection-prevention-control/ipc-and-antimicrobial-resistance",
        organisation="WHO",
        scraping_method="scrapy",
        expertise_level="intermediate",
        content_category="action_plan",
        document_format="html",
        authority_tier=1,
        crawl_depth=2,
    ),
    SourceConfig(
        source_id="who-caesar-surveillance",
        title="CAESAR - Central Asian and European Surveillance of AMR",
        url="https://www.who.int/europe/groups/central-asian-and-european-surveillance-of-antimicrobial-resistance-(caesar)",
        organisation="WHO Regional Office for Europe",
        scraping_method="scrapy",
        expertise_level="intermediate",
        content_category="data",
        document_format="html",
        authority_tier=1,
        crawl_depth=2,
    ),
    SourceConfig(
        source_id="cdc-core-elements-nursing-homes",
        title="Core Elements for Nursing Homes and Long-Term Care - CDC",
        url="https://www.cdc.gov/antibiotic-use/hcp/core-elements/nursing-homes/index.html",
        organisation="CDC",
        scraping_method="scrapy",
        expertise_level="intermediate",
        content_category="action_plan",
        document_format="html",
        authority_tier=1,
        crawl_depth=2,
    ),
    # --- New PDF Sources: Risk ---
    SourceConfig(
        source_id="ecdc-cre-risk-assessment",
        title="ECDC Risk Assessment on Carbapenem-Resistant Enterobacterales (2025)",
        url="https://www.ecdc.europa.eu/sites/default/files/documents/risk-assessment-carbapenem-resistant-enterobacterales-third-update-february-2025_0.pdf",
        organisation="ECDC",
        scraping_method="docling",
        expertise_level="advanced",
        content_category="risk",
        document_format="pdf",
        authority_tier=1,
    ),
    # --- New PDF Sources: Impact ---
    SourceConfig(
        source_id="woah-ecoamr-2024",
        title="Forecasting the Fallout from AMR - EcoAMR (WOAH/World Bank, 2024)",
        url="https://www.woah.org/app/uploads/2024/09/ecoamr-woah-animal-sector-web-reduced-23924.pdf",
        organisation="WOAH / World Bank",
        scraping_method="docling",
        expertise_level="intermediate",
        content_category="impact",
        document_format="pdf",
        authority_tier=1,
    ),
    # --- New PDF Sources: Action Plans & Policy ---
    SourceConfig(
        source_id="quadripartite-joint-plan-2022",
        title="One Health Joint Plan of Action 2022-2026 (Quadripartite)",
        url="https://www.woah.org/app/uploads/2022/04/one-health-joint-plan-of-action-final.pdf",
        organisation="FAO / UNEP / WHO / WOAH",
        scraping_method="docling",
        expertise_level="advanced",
        content_category="action_plan",
        document_format="pdf",
        authority_tier=1,
    ),
    SourceConfig(
        source_id="who-nap-implementation-handbook",
        title="Implementation Handbook for National Action Plans on AMR (WHO, 2022)",
        url="https://www.who.int/publications/i/item/9789240041981",
        organisation="WHO",
        scraping_method="docling",
        expertise_level="advanced",
        content_category="action_plan",
        document_format="pdf",
        authority_tier=1,
    ),
    SourceConfig(
        source_id="eu-one-health-action-plan-pdf",
        title="European One Health Action Plan Against AMR - Full PDF (2017)",
        url="https://health.ec.europa.eu/system/files/2020-01/amr_2017_action-plan_0.pdf",
        organisation="European Commission",
        scraping_method="docling",
        expertise_level="advanced",
        content_category="action_plan",
        document_format="pdf",
        authority_tier=1,
    ),
]


def get_source_by_id(source_id: str) -> SourceConfig | None:
    """Look up a source by its source_id."""
    for source in PHASE_1_SOURCES:
        if source.source_id == source_id:
            return source
    return None


def get_sources_by_method(method: str) -> list[SourceConfig]:
    """Filter sources by scraping method."""
    return [s for s in PHASE_1_SOURCES if s.scraping_method == method]
